import { Inter } from 'next/font/google';
import Header from '../components/Header';

import '../styles/style.css';

const inter = Inter({ subsets: ['latin'] });

// TODO:need update project title and description
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          <>{children}</>
        </main>
      </body>
    </html>
  );
}
